/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {
    public static void main(String[] args) {
        HashMap<String, Pessoa> mapa = new HashMap<>();

        mapa.put("123", new Pessoa("juca", "juca@example.org"));
        mapa.put("456", new Pessoa("ana", "ana@example.org"));
        mapa.put("789", new Pessoa("pedro", "pedro@example.org"));

        mapa.forEach((c,v) -> IO.println("chave: " + c + ", valor: " + v));

        var removida = mapa.remove("123");
        IO.println("foi removida a pessoa: " + removida);

        mapa.values().removeIf(e-> e.getNome().equals("juca"));
    }
}
