/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    static void main (String[] args) {
        Robo walle = new Robo(5, 5, 2, 3);
        IO.println(walle);
        IO.println(walle.deslocar(20, "N"));
        IO.println(walle.deslocar(3, "L"));
        IO.println(walle.deslocar(8, "S"));
        IO.println(walle.deslocar(100, "O"));
        IO.println(walle);
        walle.carregarBateria();
        IO.println(walle);
        IO.println(walle.deslocar(3, "O"));
        IO.println(walle.deslocar(1, "N"));
        IO.println(walle);
        walle.carregarBateria();
        IO.println(walle);
        IO.println(walle.deslocar(3, "L"));
        IO.println(walle.deslocar(1, "S"));
        IO.println(walle);
        walle.carregarBateria();
        IO.println(walle);
    }
}
