/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Pessoa fulano = new Pessoa("caio@hotmail.com", "Caio");
        Pessoa ciclano = new Pessoa("luiza@hotmail.com", "Luiza");

        IO.println(fulano.getId());
        IO.println(ciclano.getId());

        IO.println(fulano.toString());
        IO.println(ciclano.toString());
    }
}
