/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mês: ");

        switch (mes){
            case "Janeiro" -> IO.println("Verão");
            default -> IO.println("Mês inválido!");
        }
    }
}
