/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {

    private HashMap<String, Livro> livros = new HashMap<>();

    public void cadastrar(){
        String isbn;
        do {
            isbn = IO.readln("Qual o numero ISBN do livro?: ");
            if (livros.containsKey(isbn)){
                IO.println("Livro com este ISBN ja cadastrado!");
            }
        } while(livros.containsKey(isbn));
        String titulo = IO.readln("Qual o titulo do livro?: ");
        String autor = IO.readln("Qual o autor do livro?: ");
        int anoPublicacao = Integer.parseInt(IO.readln("Qual o ano de publicacao do livro?: "));
        Livro l = new Livro(isbn, titulo, autor, anoPublicacao);
        livros.put(isbn, l);
    }

    public void listar(){
        String p = String.format("| %-5s | %-15s |%n", "ISBN" , "Titulo");
        String b = "+" + "-".repeat(27-3) + "+";
        IO.println(b);
        IO.print(p);
        IO.println(b);
        for (var entrada : livros.entrySet()){
            String s = String.format("| %-5s | %-15s |%n", entrada.getKey() , entrada.getValue().getTitulo());
            IO.print(s);
        }
        IO.println(b);
    }

    public void consultar(){
        String isbn = IO.readln("Digite o numero ISBN do livro: ");
        Livro l  = livros.get(isbn);
        if (l != null){
            IO.println(l);
        } else {
            IO.println("Este numero ISBN nao existe!");
        }

    }

    public void consultaPorAutor(){
        String autor = IO.readln("Digite o nome do autor: ");
        String p = String.format("| %-5s | %-15s |", "ISBN" , "Titulo");
        String b = "+" + "-".repeat(27-3) + "+";
        IO.println(b);
        IO.println(p);
        IO.println(b);
        for (var entrada : livros.entrySet()){
            if (autor.equals(entrada.getValue().getAutor())){
                String s = String.format("| %-5s | %-15s |%n", entrada.getKey() , entrada.getValue().getTitulo());
                IO.print(s);
            }
        }
        IO.println(b);
    }

    public void consultaPorAno(){
        int ano = Integer.parseInt(IO.readln("Digite o ano de publicacao: "));
        String p = String.format("| %-5s | %-15s |", "ISBN" , "Titulo");
        String b = "+" + "-".repeat(27-3) + "+";
        IO.println(b);
        IO.println(p);
        IO.println(b);
        for (var entrada : livros.entrySet()){
            if (ano == entrada.getValue().getAnoPublicacao()){
                String s = String.format("| %-5s | %-15s |%n", entrada.getKey() , entrada.getValue().getTitulo());
                IO.print(s);
            }
        }
        IO.println(b);
    }

    public void atualizarDados(){
        String isbn = IO.readln("Digite o numero ISBN do livro: ");
        Livro l = livros.get(isbn);
        if (l != null){
            String novoTitulo = IO.readln("Digite o novo titulo: (Enter para pular)");
            if (!novoTitulo.isEmpty()){
                l.setTitulo(novoTitulo);
            }
            String novoAutor = IO.readln("Digite o novo autor: (Enter para pular)");
            if (!novoAutor.isEmpty()){
                l.setAutor(novoAutor);
            }
            String novoAnoStr = IO.readln("Digite o novo ano de publicacao: (Enter para pular)");
            if (!novoAnoStr.isEmpty()){
                int novoAno = Integer.parseInt(novoAnoStr);
                l.setAnoPublicacao(novoAno);
            }
        }
    }

    public void remover(){
        String isbn = IO.readln("Digite o numero ISBN do livro: ");
        Livro l = livros.remove(isbn);
        if (l != null){
            IO.println("Livro removido com sucesso!");
        } else {
            IO.println("Este numero ISBN nao existe!");
        }
    }

    private int menu(){
        IO.println("1 - Cadastrar livro");
        IO.println("2 - Listar todos os livros cadastrados");
        IO.println("3 - Consultar livros pelo ISBN");
        IO.println("4 - Consultar livros por autor");
        IO.println("5 - Consultar livros por ano de publicacao");
        IO.println("6 - Atualizar dados de um livro");
        IO.println("7 - Remover livro");
        IO.println("8 - Sair");
        return Integer.parseInt(IO.readln("Entre com a opção desejada: "));
    }

    public static void main(String[] args) {

        App app = new App();

        int opcao;

        do {
            opcao = app.menu();
            switch(opcao){
                case 1 -> {
                    app.cadastrar();
                }
                case 2 -> {
                    app.listar();
                }
                case 3 -> {
                    app.consultar();
                }
                case 4 -> {
                    app.consultaPorAutor();
                }
                case 5 -> {
                    app.consultaPorAno();
                }
                case 6 -> {
                    app.atualizarDados();
                }
                case 7 -> {
                    app.remover();
                }
                case 8 -> {
                    IO.println("Saindo...");
                }
                default -> {
                    IO.println("Opcao invalida!");
                }
            }
        } while (opcao != 8);
    }
}
