/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {

    private HashMap<String, Livro> livros = new HashMap<>();

    public void cadastrar(){
        String isbn;
        do {
            isbn = IO.readln("Qual o numero ISBN do livro?: ");
            if (livros.containsKey(isbn)){
                IO.println("Livro com este ISBN ja cadastrado!");
            }
        } while(livros.containsKey(isbn));
        String titulo = IO.readln("Qual o titulo do livro?: ");
        String autor = IO.readln("Qual o autor do livro?: ");
        int anoPublicacao = Integer.parseInt(IO.readln("Qual o ano de publicacao do livro?: "));
        Livro l = new Livro(isbn, titulo, autor, anoPublicacao);
        livros.put(isbn, l);
    }

    public void listar(){
        for (var entrada : livros.entrySet()){
            IO.println("ISBN: " + entrada.getKey());
            IO.println("Titulo: " + entrada.getValue().getTitulo());
        }
    }

    public void consultar(){
        String isbn = IO.readln("Digite o numero ISBN do livro: ");
        IO.println(livros.get(isbn));
    }

    public void consultaPorAutor(){
        String autor = IO.readln("Digite o nome do autor: ");
        for (var entrada : livros.entrySet()){
            if (autor.equals(entrada.getValue().getAutor())){
                IO.println("ISBN: " + entrada.getKey());
                IO.println("Titulo: " + entrada.getValue().getTitulo());
            }
        }
    }

    public void consultaPorAno(){
        int ano = Integer.parseInt(IO.readln("Digite o ano de publicacao: "));
        for (var entrada : livros.entrySet()){
            if (ano == entrada.getValue().getAnoPublicacao()){
                IO.println("ISBN: " + entrada.getKey());
                IO.println("Titulo: " + entrada.getValue().getTitulo());
            }
        }
    }

    public void atualizarDados(){
        String isbn = IO.readln("Digite o numero ISBN do livro: ");
        Livro l = livros.get(isbn);
        if (l != null){
            String novoTitulo = IO.readln("Digite o novo titulo: (Enter para pular)");
            if (!novoTitulo.isEmpty()){
                l.setTitulo(novoTitulo);
            }
            String novoAutor = IO.readln("Digite o novo autor: (Enter para pular)");
            if (!novoAutor.isEmpty()){
                l.setTitulo(novoAutor);
            }
            int novoAno = Integer.parseInt(IO.readln("Digite o novo ano: (Enter para pular)"));
        }
    }

    public static void main(String[] args) {

        App app = new App();

        app.cadastrar();
        app.cadastrar();

        app.listar();
        app.consultar();
        app.consultaPorAutor();
        app.consultaPorAno();
    }
}
