/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args){
        Batedeira electrolux = new Batedeira();

        IO.println(electrolux.obterEstadoAtual());
        electrolux.ligar();
        IO.println(electrolux.obterEstadoAtual());
        electrolux.definirCronometro(30);
        IO.println(electrolux.obterTempoAtual());
        electrolux.bater();
        IO.println(electrolux.obterEstadoAtual());
        electrolux.trocarPonteira();
        IO.println(electrolux.obterEstadoAtual());

        String ponteira = IO.readln("Escolha o tipo de ponteira que você deseja colocar (Fouet, Plana ou Espiral) : ");
        electrolux.escolherPonteira(ponteira);
        IO.println(electrolux.obterPonteiraAtual());
    }
}
